/** @format */

import { StyleSheet, Dimensions } from 'react-native';
import { Color, Fonts } from '@common';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: Color.border,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
  },
  editButton: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: '#ff8a65',
    borderRadius: 20,
  },
  editButtonText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontWeight: '500',
  },
  section: {
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: Color.border,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: Fonts.bold,
    fontWeight: '600',
    marginBottom: 12,
  },
  orderItem: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingVertical: 12,
    paddingHorizontal: 15,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    alignItems: 'flex-start',
    minHeight: 100,
  },
  productImageContainer: {
    width: 80,
    height: 80,
    marginRight: 12,
    justifyContent: 'center',
  },
  productImage: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
    backgroundColor: '#f5f5f5',
    resizeMode: 'cover',
  },
  productDetails: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  productInfoBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 8,
  },
  productInfoLeft: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  productInfoRight: {
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    minHeight: 60,
  },
  productName: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontWeight: '500',
    marginBottom: 8,
    lineHeight: 18,
    flex: 1,
  },
  productVariant: {
    fontSize: 12,
    fontFamily: Fonts.regular,
    color: Color.grey,
    marginBottom: 6,
  },
  productPrice: {
    fontSize: 13,
    fontFamily: Fonts.regular,
    fontWeight: '500',
    color: Color.text,
  },
  quantityAndTotalContainer: {
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    minHeight: 60,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  quantityLabel: {
    fontSize: 12,
    fontFamily: Fonts.regular,
    marginRight: 8,
    color: Color.grey,
  },
  quantitySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e9ecef',
    borderRadius: 15,
    paddingHorizontal: 4,
  },
  quantityButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  quantityButtonText: {
    fontSize: 16,
    fontFamily: Fonts.bold,
    color: Color.primary,
  },
  quantityText: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    marginHorizontal: 8,
    minWidth: 20,
    textAlign: 'center',
    color: Color.text,
  },
  itemTotal: {
    fontSize: 14,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
    color: Color.text,
  },
  addressContainer: {
    backgroundColor: '#f8f9fa',
    padding: 15,
    borderRadius: 8,
    marginTop: 8,
  },
  addressText: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    marginBottom: 3,
  },
  // Coupon Styles
  couponInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  couponInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    fontFamily: Fonts.regular,
    marginRight: 10,
  },
  applyCouponButton: {
    backgroundColor: Color.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  applyCouponText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontWeight: '500',
  },
  appliedCouponContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#e8f5e8',
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  appliedCouponInfo: {
    flex: 1,
  },
  appliedCouponCode: {
    fontSize: 14,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  appliedCouponDiscount: {
    fontSize: 12,
    fontFamily: Fonts.regular,
  },
  removeCouponButton: {
    backgroundColor: '#ff6b6b',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  removeCouponText: {
    color: '#fff',
    fontSize: 12,
    fontFamily: Fonts.regular,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  priceLabel: {
    fontSize: 14,
    fontFamily: Fonts.regular,
  },
  priceValue: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontWeight: '500',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: Color.border,
    marginTop: 10,
    paddingTop: 15,
  },
  totalLabel: {
    fontSize: 18,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
  },
  totalValue: {
    fontSize: 18,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
    color: Color.primary,
  },
  buttonContainer: {
    padding: 20,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: Color.border,
  },
  proceedButton: {
    backgroundColor: '#ff8a65',
    borderRadius: 8,
    paddingVertical: 15,
  },
  proceedButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
  },
});
